// generated by yagi. Don't modify this file!
// Any changes will be lost if this file is regenerated.

package main

type MapStringPint64 struct{ items map[string]*int64 }

func NewStringPint64() *MapStringPint64 {
	return &MapStringPint64{make(map[string]*int64)}
}

func (m *MapStringPint64) Put(key string, value *int64) {
	m.items[key] = value
}

func (m MapStringPint64) Get(key string) *int64 {
	return m.items[key]
}

type MapStringPint32 struct{ items map[string]*int32 }

func NewStringPint32() *MapStringPint32 {
	return &MapStringPint32{make(map[string]*int32)}
}

func (m *MapStringPint32) Put(key string, value *int32) {
	m.items[key] = value
}

func (m MapStringPint32) Get(key string) *int32 {
	return m.items[key]
}
