// generated by yagi. Don't modify this file!
// Any changes will be lost if this file is regenerated.

package set

import "fmt"

type SetInt map[int]struct{}

func (i SetInt) String() string {
	n := ""
	for i := range i {
		if len(n) > 0 {
			n += " "
		}
		n += fmt.Sprintf("%v", i)
	}
	return n
}

func (i *SetInt) Add(a int) {
	(*i)[a] = struct{}{}
}

func (i *SetInt) AddAll(a SetInt) {
	for el := range a {
		i.Add(el)
	}
}

func (i SetInt) Has(a int) bool {
	_, ok := i[a]
	return ok
}

func (i SetInt) Items() (res []int) {
	for item := range i {
		res = append(res, item)
	}
	return
}
