// generated by yagi. Don't modify this file!
// Any changes will be lost if this file is regenerated.

package gmap

type MapStringInt map[string]int

func (m MapStringInt) Get(key string) int {
	return m[key]
}

func (m MapStringInt) Put(key string, value int) {
	m[key] = value
}

type MapStringInt64 map[string]int64

func (m MapStringInt64) Get(key string) int64 {
	return m[key]
}

func (m MapStringInt64) Put(key string, value int64) {
	m[key] = value
}

type MapStringFloat64 map[string]float64

func (m MapStringFloat64) Get(key string) float64 {
	return m[key]
}

func (m MapStringFloat64) Put(key string, value float64) {
	m[key] = value
}
